### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by computeronix**
Added support for phpMyAdmin when PHP is setup to log to syslog (on windows machines it will point to Windows Event Viewer)

Fixed some typos in the configs

Allowed firewall reviewing in the Event Viewer by default

### CODE REVIEW

**Comment by Rambaldi** [comment]
hi, i have thi error
WARN|FileLogger|Regex (3) did not match any nodes with xpath //EventID

**Comment by computeronix** [comment]
The warnings are normal they just saying did not match rule
Should really be INFO logs and will modify this later
I modified the phpmyadmin regex rule now to be more descriptive so now it willl say 
WARN|FileLogger|Regex phpMyAdmin did not match any nodes with xpath //Data

**Comment by Rambaldi** [comment]
Yes, thank you

**Comment by jjxtra** [comment]
Looks great, I've merged it into the main branch

**Pull request merged**
